#
# embedXcode
# ----------------------------------
# Embedded Computing on Xcode
#
# Copyright © Rei VILO, 2010-2016
# http://embedxcode.weebly.com
# All rights reserved
#
# Last update: Oct 28, 2016 release 5.3.5
#

# ----------------------------------
# DO NOT EDIT THIS FILE.
# ----------------------------------

EMBEDXCODE_RELEASE              = 5.3.5
EMBEDXCODE_DATE                 = Oct 28, 2016
EMBEDXCODE_MESSAGE              = Updated support for Xcode 8.1


# ~
EMBEDXCODE_EDITION      = embedXcode for Wiring / Arduino
EMBEDXCODE_REFERENCE    = embedXcode
EMBEDXCODE_TEMPLATE     = ePsiEJEtRXnDNaFGpywBX9vzeNQP4vUb
# ~~


# Arduino.ORG
# ----------------------------------
#
ARDUINO_ORG_RELEASE             = 1.7.11


# Arduino.CC or Genuino with Boards Manager
# ----------------------------------
#
ARDUINO_CC_RELEASE              = 1.6.12

ARDUINO_AVR_RELEASE             = 1.6.14
AVR_GCC_RELEASE                 = 4.9.2-atmel3.5.3-arduino2
AVRDUDE_RELEASE                 = 6.0.1-arduino5

# Boards for Arduino.CC 1.6.5 or Genuino
#
ADAFRUIT_AVR_RELEASE            = 1.4.9
ADAFRUIT_SAMD_RELEASE           = 1.0.13

ARDUCAM_ESP_RELEASE             = 2.2.0
ARDUCAM_ESP_TOOLS_RELEASE       = 0.4.8
ARDUCAM_ESP_MKSPIFFS_RELEASE    = 0.1.2
ARDUCAM_ESP_EXTENSA_RELEASE     = 1.20.0-26-gb404fb9-2

ARDUINO_AVR_RELEASE             = 1.6.14
AVR_GCC_RELEASE                 = 6.3.0-arduino6
AVRDUDE_RELEASE                 = 4.9.2-atmel3.5.3-arduino2

ARDUINO_SAM_RELEASE             = 1.6.9
ARDUINO_SAMD_RELEASE            = 1.6.8
ARM_GCC_RELEASE                 = 4.8.3-2014q1
BOSSAC_RELEASE                  = 1.7.0
CMSIS_RELEASE                   = 4.0.0-atmel
OPENOCD_RELEASE                 = 0.9.0-arduino

CHIPKIT_RELEASE                 = 1.3.1
PIC32_GCC_RELEASE               = 1.42-pic32gcc
PIC32_PROG_RELEASE              = v2.1.24

COSA_AVR_RELEASE                = 1.2.0

DIGISTUMP_AVR_RELEASE           = 1.6.7
DIGISTUMP_OAK_RELEASE           = 1.0.6
DIGISTUMP_SAM_RELEASE           = 1.6.5
DIGISTUMP_OAK_ESPTOOLS_RELEASE  = 0.9.1
DIGISTUMP_OAK_MKSPIFFS_RELEASE  = 0.1.2
DIGISTUMP_OAK_OAKCLI_RELEASE    = 1.0.2
DIGISTUMP_OAK_EXTENSA_RELEASE   = 1.20.0-26-gb404fb9-2

ESP8266_RELEASE                 = 2.3.0
ESPTOOLS_RELEASE                = 0.4.9
EXTENSA_RELEASE                 = 1.20.0-26-gb404fb9-2

INTEL_EDISON_RELEASE            = 1.6.7+1.0
INTEL_GALILEO_RELEASE           = 1.6.7+1.0
INTEL_CURIE_RELEASE             = 1.0.7
INTEL_ARC_RELEASE               = 1.6.9+1.0.1
INTEL_CORE2_RELEASE             = 1.6.2+1.0
INTEL_I586_RELEASE              = 1.6.2+1.0
INTEL_UPLOAD_RELEASE            = 1.6.2+1.0
INTEL_CURIE_UPLOAD_RELEASE      = 1.6.9+1.28

LINKIT_ONE_RELEASE              = 1.1.23
LINKIT_DUO_RELEASE              = 0.1.8

LITTLEROBOTFRIENDS_AVR_RELEASE  = 1.6.0

MOTEINO_AVR_RELEASE             = 1.2.0

PANSTAMP_AVR_RELEASE            = 1.5.6
PANSTAMP_MSP_RELEASE            = 1.0.7

REDBEARLAB_DUO_RELEASE          = 0.2.10
DUO_GCC_ARM_RELEASE             = 4.9-2015-q3
REDBEARLAB_AVR_RELEASE          = 1.0.3
REDBEARLAB_NRF_RELEASE          = 1.0.7
NRF_GCC_ARM_RELEASE             = 4.9-2015-q3

RFDUINO_RELEASE                 = 2.3.1
SIMBLEE_RELEASE                 = 1.1.0

UDOO_NEO_RELEASE                = 1.6.6-00014-ga77fef4
UDOO_GCC_ARM_RELEASE            = 4.9-2014q4-20141203
UDOO_CLIENT_RELEASE             = 1.0


# Energia with Boards Manager
# ----------------------------------
#
ENERGIA_IDE_RELEASE             = 1.6.10E18

ENERGIA_MSP430_RELEASE          = 1.0.1

# Boards for Energia 0165E0018
#
ENERGIA_CC1310_EMT_RELEASE      = 3.6.1
ENERGIA_CC3200_RELEASE          = 1.0.2
ENERGIA_MSP432_EMT_RELEASE      = 1.3.3
ENERGIA_TIVAC_RELEASE           = 1.0.2
ENERGIA_GCC_RELEASE             = 4.8.4-20140725
ENERGIA_CC3200_PROG_RELEASE     = 1.1.4
ENERGIA_DSLITE_RELEASE          = 6.2.1.1624

